// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://levpqumsnsqicxkjdlvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldnBxdW1zbnNxaWN4a2pkbHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4OTk3OTUsImV4cCI6MjA3NzQ3NTc5NX0.xGqYvL1OHsddrlQoXo33uiBy61r_1jIbrYo2t7hh2I4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});